#include "DungeonActors.h"
#include "Kismet/GameplayStatics.h"

// Stable IDs: 24 weapons, 12 armors, 12 amulets, 12 rings, and 3 per new armor slot.
// Values describe base identity;
// rolled values are stored on the item instance, never regenerated by UI or equipment.
namespace {
struct FBaseLoot { const TCHAR* Name; float Power,Speed; int32 Effect; };
const FBaseLoot Catalog[]={
 {TEXT("Keepsteel"),10,0,1},{TEXT("Gravebreaker"),15,-.1f,9},{TEXT("Cinderbrand"),12,0,7},{TEXT("Cutpurse"),7,.22f,4},
 {TEXT("Duelist's Needle"),9,.15f,6},{TEXT("Corsair Sabre"),11,.08f,5},{TEXT("Butcher's Edge"),17,-.15f,1},{TEXT("Bellringer"),20,-.2f,7},
 {TEXT("Adder's Kiss"),8,.2f,2},{TEXT("Crimson Oath"),13,0,4},{TEXT("Winterbite"),12,.05f,3},{TEXT("Stormcall"),16,-.1f,7},
 {TEXT("Briar Pike"),14,-.05f,2},{TEXT("Ossuary Axe"),18,-.15f,9},{TEXT("Silver Oath"),20,-.2f,10},{TEXT("Night Reaper"),19,-.18f,8},
 {TEXT("Sunblade"),15,0,5},{TEXT("Moonhook"),9,.18f,3},{TEXT("Blackwater"),12,.1f,6},{TEXT("Emerald Cleaver"),17,-.1f,2},
 {TEXT("Runebreaker"),22,-.25f,7},{TEXT("Bloodthorn"),15,0,1},{TEXT("Widow's Fang"),8,.25f,8},{TEXT("King's Reckoning"),23,-.25f,9},
 {TEXT("Wayfarer Leathers"),7,.05f,6},{TEXT("Keepwatch Mail"),10,0,10},{TEXT("Sentinel Plate"),14,-.02f,10},{TEXT("Verdant Scale"),11,0,5},
 {TEXT("Crimson Bulwark"),15,-.03f,4},{TEXT("Winterweave"),8,.03f,3},{TEXT("Warden Carapace"),16,-.04f,10},{TEXT("Sunforged Plate"),15,0,5},
 {TEXT("Frosthide"),12,0,3},{TEXT("Duskweave"),9,.04f,8},{TEXT("Copperguard"),11,0,7},{TEXT("Bonewarden"),14,0,9},
 {TEXT("Ruby Heart"),18,0,4},{TEXT("Emerald Vow"),18,0,2},{TEXT("Sapphire Ward"),18,0,3},{TEXT("Amethyst Eye"),16,0,8},
 {TEXT("Gravekeeper's Token"),20,0,5},{TEXT("Solar Seal"),18,0,10},{TEXT("Lunar Tear"),16,0,6},{TEXT("Eagle's Oath"),18,0,7},
 {TEXT("Last Cuppa"),22,0,5},{TEXT("Briarheart"),20,0,1},{TEXT("Aegis Medal"),20,0,10},{TEXT("Amber Hourglass"),16,.05f,6},
 {TEXT("Thornblood"),0,0,0},{TEXT("Serpent's Coil"),0,0,0},{TEXT("Skyrunner"),0,0,0},{TEXT("Vampire's Vow"),0,0,0},
 {TEXT("Iron Oath"),0,0,0},{TEXT("Amberheart"),0,0,0},{TEXT("Crimson Briar"),0,0,0},{TEXT("Venomwell"),0,0,0},
 {TEXT("Gale Knot"),0,0,0},{TEXT("Nightfeast"),0,0,0},{TEXT("Black Bastion"),0,0,0},{TEXT("Dawnheart"),0,0,0},
 {TEXT("Ranger's Cowl"),.10f,0,0},{TEXT("Keepwatch Helm"),.12f,0,0},{TEXT("Helm of Endurance"),.14f,0,0},
 {TEXT("Duelist's Grips"),.07f,0,0},{TEXT("Swiftsteel Gauntlets"),.09f,0,0},{TEXT("Amberstrike Gloves"),.11f,0,0},
 {TEXT("Trailguard Trousers"),5,0,0},{TEXT("Sentinel Legplates"),7,0,0},{TEXT("Bastion Greaves"),9,0,0},
 {TEXT("Trailrunner Boots"),.05f,0,0},{TEXT("Windstep Sabatons"),.07f,0,0},{TEXT("Stormstriders"),.09f,0,0}
};
static_assert(UE_ARRAY_COUNT(Catalog)==DungeonLootCatalog::Count);
}
FString FDungeonItem::EffectText() const
{
 const TCHAR* Texts[]={TEXT(""),TEXT("10% on hit: Bleed, 20% damage/sec for 4s"),TEXT("10% on hit: Poison, 14% damage/sec for 6s"),
 TEXT("Chill: slow movement 35% for 3s"),TEXT("Leech: heal 2.5% of direct damage; shared heal cap"),TEXT("Harvest: heal 2 health per kill; shared heal cap"),
 TEXT("Second wind: critical hits restore 6 stamina"),TEXT("Echo: every third strike splashes 35% damage"),
 TEXT("Execute: +35% damage below 30% enemy health"),TEXT("Berserk: +30% damage below 40% health"),
 TEXT("Aegis: reduce incoming damage by 8%")};
 return Texts[FMath::Clamp(Effect,0,10)];
}
float FDungeonItem::EquippedScale() const
{
 // Inventory icons are normalized for readability, not physical weapon size.
 // Scale around the grip in the renderer so resizing never moves the hand anchor.
 const float Scales[]={.90f,.82f,.90f,.68f,.82f,.85f,.80f,.78f,
     .67f,.90f,.86f,.80f,.86f,.80f,.94f,.83f,
     .90f,.72f,.84f,.82f,.80f,.86f,.66f,.94f};
 return CatalogId>=0&&CatalogId<24?Scales[CatalogId]:Icon==1?.85f:.92f;
}
FDungeonItem ADungeonGameMode::RollItem(int32 Definition,int32 Rarity,int32 Level)
{
 FDungeonItem I; I.CatalogId=FMath::Clamp(Definition,0,DungeonLootCatalog::Count-1); I.ItemLevel=FMath::Clamp(Level,1,100);
 I.Rarity=FMath::Clamp(Rarity,0,4); const auto& B=Catalog[I.CatalogId]; I.Name=B.Name;
 I.Slot=I.CatalogId<24?0:I.CatalogId<36?1:I.CatalogId<48?2:I.CatalogId<60?3:4+(I.CatalogId-60)/3;
 I.Icon=I.Slot*3+(I.CatalogId%3);
 const float Scale=DungeonBalance::PrimaryScale(I.ItemLevel,I.Rarity)*FMath::FRandRange(.94f,1.06f);
 if(I.Slot==0) { I.Attack=B.Power*Scale; I.Speed=B.Speed; }
 if(I.Slot==1) { I.Defense=B.Power*Scale; I.Vitality=8*Scale; I.Speed=B.Speed; }
 if(I.Slot==2) I.Vitality=B.Power*Scale;
 const float PercentScale=DungeonBalance::PercentScale(I.ItemLevel,I.Rarity)*FMath::FRandRange(.95f,1.05f);
 if(I.Slot==4) I.StaminaBonus=B.Power*PercentScale;
 if(I.Slot==5) I.Speed=B.Power*PercentScale;
 if(I.Slot==6) I.Defense=B.Power*Scale;
 if(I.Slot==7) I.Movement=B.Power*PercentScale;
 if(I.Slot==3) {
  const float Q=FMath::FRandRange(.9f,1.1f)*(1+.22f*I.Rarity);
  switch((I.CatalogId-48)%6) {
   case 0:I.BleedChance=.04f*Q;break; case 1:I.PoisonChance=.04f*Q;break;
   case 2:I.StaminaBonus=.12f*Q;break; case 3:I.Leech=.012f*Q;break;
   case 4:I.Reduction=.05f*Q;break; case 5:I.HealthBonus=.10f*Q;break;
  }
 }
 // Shuffle without replacement: no duplicate affix on one item.
 TArray<int32> Pool={0,1,2,3,4,5};
 for(int N=0;N<FMath::Min(I.Rarity,3);++N)
 {
  int Pick=FMath::RandRange(0,Pool.Num()-1),Affix=Pool[Pick]; Pool.RemoveAt(Pick);
  const float Q=FMath::FRandRange(.75f,1.f)*(1+.15f*I.Rarity);
  switch(Affix) {
   case 0:I.CritChance+=.018f*Q;break; case 1:I.CritDamage+=.12f*Q;break;
   case 2:I.Speed+=.045f*Q;break; case 3:I.Regen+=.10f*Q;break;
   case 4:I.Vitality+=8*Q;break; case 5:I.Defense+=3*Q;break;
  }
 }
 // Rare/epic signature effects let players try ailment builds before legendary drops.
 if(I.Rarity==4||(I.Rarity>=2&&FMath::FRand()<.3f)) I.Effect=B.Effect;
 I.CoinValue=FMath::RoundToInt(1.5f*(30+I.ItemLevel*12)*(1+I.Rarity*1.8f)*FMath::FRandRange(.9f,1.1f));
 return I;
}
bool ADungeonHero::HasEffect(int32 Effect) const
{ for(const auto& I:Equipment) if(!I.IsEmpty()&&I.Effect==Effect) return true; return false; }
void ADungeonHero::RebuildStats()
{
 AttackPower=24;Armor=8;MaxHealth=150;CritChance=.05f;CritMultiplier=1.5f;AttackSpeed=StaminaRegen=MovementSpeed=1;
 MaxStamina=100;BleedChance=PoisonChance=Leech=DamageReduction=0;
 float HPBonus=0,SPBonus=0;
 for(const auto& I:Equipment) if(!I.IsEmpty()) { BleedChance+=I.BleedChance;PoisonChance+=I.PoisonChance;Leech+=I.Leech;DamageReduction+=I.Reduction;HPBonus+=I.HealthBonus;SPBonus+=I.StaminaBonus; }
 for(const auto& I:Equipment) if(!I.IsEmpty()) { AttackPower+=I.Attack;Armor+=I.Defense;MaxHealth+=I.Vitality;CritChance+=I.CritChance;CritMultiplier+=I.CritDamage;AttackSpeed+=I.Speed;StaminaRegen+=I.Regen; }
 for(const auto& I:Equipment)if(!I.IsEmpty())MovementSpeed+=I.Movement;
 MovementSpeed=FMath::Clamp(MovementSpeed,1.f,1.35f);
 CritChance=FMath::Clamp(CritChance,0.f,.45f);AttackSpeed=FMath::Clamp(AttackSpeed,.5f,1.65f);
 MaxHealth*=1+FMath::Clamp(HPBonus,0.f,1.f);MaxStamina*=1+FMath::Clamp(SPBonus,0.f,1.f);
 BleedChance=FMath::Clamp(BleedChance+(HasEffect(1)?.1f:0),0.f,.35f);
 PoisonChance=FMath::Clamp(PoisonChance+(HasEffect(2)?.1f:0),0.f,.35f);
 Leech=FMath::Clamp(Leech,0.f,.06f);DamageReduction=FMath::Clamp(DamageReduction,0.f,.30f);
 Stamina=FMath::Clamp(Stamina,0.f,MaxStamina);
 Health=FMath::Clamp(Health,0.f,MaxHealth);
}
void ADungeonEnemy::UpdateAilments(float Dt)
{
 const float Damage=FMath::Min(Dt,BleedTime)*BleedDPS+FMath::Min(Dt,PoisonTime)*PoisonDPS;
 BleedTime=FMath::Max(0.f,BleedTime-Dt);PoisonTime=FMath::Max(0.f,PoisonTime-Dt);SlowTime=FMath::Max(0.f,SlowTime-Dt);
 // One non-proccing damage application. Death callback fires only through normal damage path.
 AilmentDamage+=Damage; AilmentTick+=Dt;
 if(AilmentDamage>0&&(AilmentTick>=.5f||(BleedTime<=0&&PoisonTime<=0)))
 { const float Pending=AilmentDamage; AilmentDamage=AilmentTick=0; TakeDungeonDamage(Pending); }
}
