"""Build isolated runtime atlases from measured crops for user-approved playtesting.
Does not mark the source artwork as final animation approval.
"""
from pathlib import Path
import json, statistics, math
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'ArtSource/HeroFullBodyV1'
OUT=ART/'runtime-test';OUT.mkdir(exist_ok=True)
clips=['Idle','Walk','Run','MeleeSlash','MeleeBackhand','MeleeCombo','Block','Roll','TeaThrow','PotionDrink','GoldenTeaDrink','BowIdle','BowWalk','BowRun','BowDrawFire','Hurt','DeathRecover','BowBlock','BowStow']
names=[];all_metrics=[];records=[]
for clip in clips:
    for direction in range(8):
        name=f'{clip}_{direction}'
        source='Walk_SE_corrected' if name=='Walk_3' else name
        frames=[Image.open(ART/'crops'/source/f'{f:02}.png').convert('RGBA') for f in range(8)]
        landmarks=json.loads((ART/'landmarks'/f'{source}.json').read_text())['frames']
        # One scale per authored sheet: crouches and rolls must not inflate to
        # standing height. Corrected single-pose walk sources have mixed sizes.
        base=max(im.height for im in frames)
        atlas=Image.new('RGBA',(1024,512));metrics=[]
        for f,im in enumerate(frames):
            lm=landmarks[f]['landmarks']
            scale=220/(im.height if source=='Walk_SE_corrected' else base)
            scale=min(scale,244/im.width,236/im.height)
            hip=statistics.mean(lm[k]['xy'][0] for k in ['leftHip','rightHip']) if lm else im.width/2
            if clip in ['Roll','DeathRecover']:hip=im.width/2
            w,h=round(im.width*scale),round(im.height*scale)
            x=round(128-hip*scale);x=max(6,min(250-w,x));y=232-h
            cell=Image.new('RGBA',(256,256));cell.alpha_composite(im.resize((w,h),Image.Resampling.LANCZOS),(x,y))
            atlas.alpha_composite(cell,((f%4)*256,(f//4)*256))
            def point(key,fallback):
                return (x+lm[key]['xy'][0]*scale,y+lm[key]['xy'][1]*scale) if key in lm else fallback
            wrist=point('rightWrist',(128,148));elbow=point('rightElbow',(wrist[0],wrist[1]-18))
            index=point('rightIndex',wrist);pinky=point('rightPinky',wrist)
            hand=tuple(.2*wrist[a]+.4*index[a]+.4*pinky[a] for a in range(2))
            left=point('leftIndex',point('leftWrist',(128,148)))
            # Handle axis crosses the closed fingers, rather than following the forearm.
            axis=(index[0]-pinky[0],index[1]-pinky[1])
            angle=math.degrees(math.atan2(axis[1],axis[0]))+90 if math.hypot(*axis)>1 else 0
            angle=(angle+180)%360-180
            if clip in ['Idle','Walk','Run','Block']:
                if angle>90:angle-=180
                if angle<-90:angle+=180
                angle=max(-65,min(65,angle))
            metrics.append([*hand,angle,*left])
            records.append({'clip':name,'frame':f,'source':source,'scale':scale,'offset':[x,y],'root':[128,232],'hand':hand,'muzzle':left,'estimated':True})
        asset='FullBody_'+name;atlas.save(OUT/f'{asset}.png');names.append(asset);all_metrics.append(metrics)
lines=['// Generated by Tools/prepare_fullbody_test.py. Playtest registration, not art certification.','#pragma once','#include "CoreMinimal.h"','namespace FullBodyArt {', 'enum Clip { '+','.join(clips)+' };','struct Socket { float X,Y,Angle,MX,MY; };','inline constexpr Socket Sockets[152][8] = {']
for metrics in all_metrics:lines.append('{'+','.join('{'+','.join(f'{v:.3f}f' for v in values)+'}' for values in metrics)+'},')
lines+=['};','inline const TCHAR* Names[] = {'+','.join('TEXT("'+n+'")' for n in names)+'};','}']
(ROOT/'Source/TheBeardAndBlade/FullBodyArtMetrics.h').write_text('\n'.join(lines))
(OUT/'manifest.json').write_text(json.dumps(names,indent=2))
(OUT/'registration.json').write_text(json.dumps({'status':'user-approved-in-game-test-estimated-anchors','frames':records},indent=2))
print(f'Prepared {len(names)} atlases / {len(records)} frames; original assets untouched.')
