"""Generate render-only torso registration; preserve authored art and crop masks.

Match the central torso to the direction's neutral pose, not the alternating
lowest foot or the weapon silhouette. Death poses retain their authored fall.
"""
import json
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw

ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'ArtSource/EnemyExpansion'
OUT=BASE/'HomePCHandoff-v2/anchor-review'
OUT.mkdir(exist_ok=True)
names=[e['folder'] for e in json.loads((BASE/'HomePCHandoff-v2/inventory.json').read_text())['enemies']]
dirs=['N','NE','E','SE','S','SW','W','NW']
states=['idle','walk','attack','hurt','ranged']
lines=['// Generated by Tools/register_expansion_anchors.py. Atlas-pixel offsets.', '#pragma once', 'namespace DungeonExpansionAnchors {', 'inline constexpr float Offset[25][8][5][24][2]={']
report=[]
for name in names:
    records=json.loads((BASE/name/'runtime-v2/runtime-manifest.json').read_text())
    def poses(d,s):
        r=next((r for r in records if r['direction']==d and r['state']==s),None)
        if not r:return []
        im=Image.open(ROOT/'Content/Art/EnemyExpansion'/name/(r['name']+'.png')).convert('RGBA')
        cell=r['cell']
        return [im.crop(((i%4)*cell,(i//4)*cell,(i%4+1)*cell,(i//4+1)*cell)).resize((384,384),Image.Resampling.NEAREST) for i in range(r['frames'])]
    data=[]; board=Image.new('RGB',(16*160,8*160),(24,30,27))
    for di,d in enumerate(dirs):
        idle=poses(d,'idle');ref=np.array(idle[0].resize((192,192)),dtype=np.float32)/255
        # Torso core excludes most weapon motion, legs, cape tips and raised arms.
        ys,xs=np.nonzero(ref[:,:,3]>.5)
        height=ys.max()-ys.min();cy=int(169-height*.55)
        core=ref[max(0,cy-9):cy+10,88:105]
        weight=core[:,:,3:4]
        allstates=[]
        for si,s in enumerate(states):
            ims=poses(d,s);offsets=[];scores=[]
            for fi,im in enumerate(ims):
                a=np.array(im.resize((192,192)),dtype=np.float32)/255
                # Translation registration with a mild displacement penalty.
                best=(float('inf'),0,0)
                for dy in range(-9,10):
                    for dx in range(-16,17):
                        patch=a[cy-9+dy:cy+10+dy,88+dx:105+dx]
                        error=float((((patch-core)**2)*weight).sum()/max(1,weight.sum()))+.00006*(dx*dx+dy*dy)
                        if error<best[0]:best=(error,dx,dy)
                offsets.append([-2*best[1],-2*best[2]])
                scores.append(best[0])
            # Occluded torsos during a strike are not reliable registration targets.
            # Interpolate their anchors from confident neighboring poses instead
            # of snapping toward a weapon or an empty background patch.
            good=[i for i,v in enumerate(scores) if v<.18 and abs(offsets[i][0])<32 and abs(offsets[i][1])<18]
            for fi in range(len(ims)):
                if fi not in good and good:
                    offsets[fi]=[round(float(np.interp(fi,good,[offsets[j][axis] for j in good]))) for axis in range(2)]
                elif not good:offsets[fi]=[0,0]
                report.append({'enemy':name,'direction':d,'state':s,'frame':fi,'offset':offsets[fi],'error':round(scores[fi],4),'interpolated':fi not in good})
            for fi,im in enumerate(ims):
                if s=='walk':
                    corrected=Image.new('RGBA',(384,384));corrected.alpha_composite(im,tuple(offsets[-1]))
                    # Show torso anchor and full pose at normal on-screen scale.
                    tile=corrected.crop((112,195,272,355))
                    board.paste(tile,(fi*160,di*160),tile)
            offsets += [[0,0]]*(24-len(offsets));allstates.append(offsets)
        data.append(allstates)
    lines.append(json.dumps(data,separators=(',',':')).replace('[','{').replace(']','}')+',')
    board.save(OUT/(name+'-registered-walk.png'))
    before=poses('SW','walk')
    if before:
        movie=[]
        for fi,im in enumerate(before):
            off=data[5][1][fi];after=Image.new('RGBA',(384,384));after.alpha_composite(im,tuple(off))
            pair=Image.new('RGB',(360,200),(24,30,27));draw=ImageDraw.Draw(pair)
            for j,pose in enumerate([im,after]):
                patch=pose.crop((102,175,282,355));pair.paste(patch,(j*180,20),patch)
                draw.line((j*180+90,20,j*180+90,199),fill=(55,65,55))
                draw.text((j*180+5,4),'Before' if j==0 else 'Torso registered',fill='white')
            movie.append(pair)
        movie[0].save(OUT/(name+'-before-after.gif'),save_all=True,append_images=movie[1:],duration=80,loop=0)
    print(name,flush=True)
lines += ['};','inline FVector2D Get(int S,int D,const FString& State,int F){', 'int A=State==TEXT("idle")?0:State==TEXT("walk")?1:State==TEXT("attack")?2:State==TEXT("hurt")?3:State==TEXT("ranged")?4:-1;', 'if(S<54||S>78||D<0||D>7||A<0||F<0||F>=24)return FVector2D::ZeroVector;', 'return {Offset[S-54][D][A][F][0],Offset[S-54][D][A][F][1]};','}','}']
(ROOT/'Source/TheBeardAndBlade/DungeonExpansionAnchors.h').write_text('\n'.join(lines)+'\n')
(OUT/'registration.json').write_text(json.dumps(report,indent=2)+'\n')
fxboard=Image.new('RGB',(5*260,5*200),(24,30,27));draw=ImageDraw.Draw(fxboard)
for i,name in enumerate(names):
    path=ROOT/'Content/Art/EnemyExpansion'/name/(name+'_FX_projectile_atlas.png')
    if path.exists():
        im=Image.open(path).convert('RGBA').crop((0,0,384,384)).resize((230,170))
        x,y=i%5*260,i//5*200;fxboard.paste(im,(x,y),im);draw.text((x+5,y+175),name,fill='white')
fxboard.save(OUT/'projectile-directions.png')
